// Generated by CoffeeScript 1.10.0
(function() {
  var convertToText, decimals, getDecimals, getHundreds, hundreds, initialCheck, isNumber, processInput, tens, thousands, toWords, tooLarge, units;

  initialCheck = function(number) {
    if (number == null) {
      return true;
    }
    if (!isNumber(number)) {
      return true;
    }
    if (isNaN(number)) {
      return true;
    }
    if (tooLarge(number)) {
      return true;
    }
  };

  isNumber = function(number) {
    var initNumber;
    initNumber = +number;
    return typeof initNumber === 'number' || initNumber.constructor === Number;
  };

  tooLarge = function(number) {
    return number > 8999999999999999;
  };

  hundreds = ['', 'сто', 'двести', 'триста', 'четыреста', 'пятьсот', 'шестьсот', 'семьсот', 'восемьсот', 'девятьсот'];

  tens = ['', 'десять', 'двадцать', 'тридцать', 'сорок', 'пятьдесят', 'шестьдесят', 'семьдесят', 'восемьдесят', 'девяносто'];

  units = ['', 'один', 'два', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять'];

  decimals = ['', 'одиннадцать', 'двенадцать', 'тринадцать', 'четырнадцать', 'пятнадцать', 'шестнадцать', 'семнадцать', 'восемнадцать', 'девятнадцать'];

  thousands = [['', '', ''], ['тысяча', 'тысячи', 'тысяч'], ['миллион', 'миллиона', 'миллионов'], ['миллиард', 'миллиарда', 'миллиардов'], ['триллион', 'триллиона', 'триллионов'], ['квадриллион', 'квадриллиона', 'квадриллионов'], ['квинтиллион', 'квинтиллиона', 'квинтиллионов']];

  getDecimals = function(number) {
    var decimal, left, right;
    decimal = number % 100;
    if ((10 < decimal && decimal < 20)) {
      return "" + decimals[decimal % 10];
    }
    right = decimal % 10;
    left = (decimal - right) / 10;
    return (tens[left] + " " + units[right]).trim();
  };

  getHundreds = function(number) {
    return hundreds[Math.floor(number / 100)];
  };

  processInput = function(number) {
    var k, num, remain, res, results;
    remain = 0;
    results = [];
    for (num = k = 1; k <= 7; num = ++k) {
      res = Math.floor(((number - remain) % Math.pow(1000, num)) / Math.pow(1000, num - 1));
      remain += res;
      results.push(res);
    }
    return results;
  };

  convertToText = function(number, i) {
    var j;
    if (number === 0) {
      return '';
    }
    j = 2;
    return ((getHundreds(number)) + " " + (getDecimals(number)) + " " + thousands[i][j]).trim();
  };

  toWords = function(numberString) {
    var group, i, k, len, numArray, number, result;
    if (initialCheck(numberString)) {
      return null;
    }
    number = +numberString;
    if (number === 0) {
      return 'ноль';
    }
    numArray = processInput(number);
    result = [];
    for (i = k = 0, len = numArray.length; k < len; i = ++k) {
      group = numArray[i];
      result.push(convertToText(group, i));
    }
    return result.reverse().join(' ').trim();
  };

  module.exports = toWords;

}).call(this);
