// Generated by CoffeeScript 1.10.0
(function() {
  var checkRow, toWords;

  toWords = require('../2words');

  checkRow = function(row) {
    var number, results, text;
    results = [];
    for (number in row) {
      text = row[number];
      results.push(expect(toWords(number)).toBe(text));
    }
    return results;
  };

  describe('initial checks', function() {
    it('should null if given null', function() {
      var iNull;
      iNull = toWords(null);
      return expect(iNull).toBeNull();
    });
    it('should null if given undefined', function() {
      var iUnd;
      iUnd = toWords(void 0);
      return expect(iUnd).toBeNull();
    });
    it('should null if not a number', function() {
      var text;
      text = toWords('hello');
      return expect(text).toBeNull();
    });
    return it('should null if too large', function() {
      var hugeNumber;
      hugeNumber = toWords(9999999999999999);
      return expect(hugeNumber).toBeNull();
    });
  });

  describe('Convertion tests', function() {
    it('should return correct text on numbers for 1 to 20', function() {
      return checkRow({
        0: 'ноль',
        1: 'один',
        2: 'два',
        3: 'три',
        4: 'четыре',
        5: 'пять',
        6: 'шесть',
        7: 'семь',
        8: 'восемь',
        9: 'девять',
        10: 'десять',
        11: 'одиннадцать',
        12: 'двенадцать',
        13: 'тринадцать',
        14: 'четырнадцать',
        15: 'пятнадцать',
        16: 'шестнадцать',
        17: 'семнадцать',
        18: 'восемнадцать',
        19: 'девятнадцать',
        20: 'двадцать'
      });
    });
    it('should return just names of hundreds', function() {
      return checkRow({
        100: 'сто',
        200: 'двести',
        300: 'триста',
        400: 'четыреста',
        500: 'пятьсот',
        600: 'шестьсот',
        700: 'семьсот',
        800: 'восемьсот',
        900: 'девятьсот'
      });
    });
    it('should return correct text for different numbers from 100 to 999', function() {
      return checkRow({
        111: 'сто одиннадцать',
        205: 'двести пять',
        325: 'триста двадцать пять',
        563: 'пятьсот шестьдесят три',
        999: 'девятьсот девяносто девять'
      });
    });
    return it('should return correct text for different numbers from 1000 to 9999999', function() {
      return checkRow({
        222001: 'двести двадцать две тысячи один',
        410000: 'четыреста десять тысяч'
      });
    });
  });

}).call(this);
